name: video-server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: rdc-snapshots
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        env:
          MAVEN_USER_NAME: ${{ secrets.MAVEN_USER_NAME }}
          MAVEN_USER_PASSWORD: ${{ secrets.MAVEN_USER_PASSWORD }}
        run: |
          ls /usr/share
          mv /usr/share/apache-maven-3.8.7/conf/settings.xml /usr/share/apache-maven-3.8.7/conf/settings.xml.bak
          cp maven-settings.xml /usr/share/apache-maven-3.8.7/conf/settings.xml
          mvn clean deploy -DskipTests
          cp target/video-server-0.0.1-SNAPSHOT.jar docker/video-server-0.0.1-SNAPSHOT.jar
          cd docker
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/binhow/video-server
          docker login --username=${{ secrets.DOCKER_USER_NAME }} --password=${{ secrets.DOCKER_USER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker push registry.cn-hangzhou.aliyuncs.com/binhow/video-server